NumPy array reshaping simply means changing the shape of an array without changing its data.

In [1]:
import numpy as np

In [2]:
array1 = np.array([1, 3, 5, 7, 2, 4, 6, 8])

In [3]:
print(array1)

[1 3 5 7 2 4 6 8]


syntax: np.reshape(array, newshape, order = 'C')

In [7]:
newArr = np.reshape(array1, (2,2,2), order= 'C')

In [8]:
print(newArr)

[[[1 3]
  [5 7]]

 [[2 4]
  [6 8]]]


In [9]:
newArr = np.reshape(array1, (2,4), order= 'C')

In [10]:
print(newArr)

[[1 3 5 7]
 [2 4 6 8]]


In [13]:

array2 = np.array([[1, 3], [5, 7], [9, 11]])
result2 = np.reshape(array2, -1)
print("Flattened 2D array:", result2)

# flatten 3D array to 1D
array3 = np.array([[[1, 3], [5, 7]], [[2, 4], [6, 8]]])
result3 = np.reshape(array3, -1)
print("Flattened 3D array:", result3)

Flattened 2D array: [ 1  3  5  7  9 11]
Flattened 3D array: [1 3 5 7 2 4 6 8]
