NumPy Array Manipulation Functions

NumPy array manipulation functions allow us to modify or rearrange NumPy arrays. For example,

In [2]:
import numpy as np


array1 = np.array([1, 3, 5, 7, 9, 11])

array2 = np.reshape(array1, (2, 3))

array3 = np.transpose(array2)

print("Original array:\n", array1)
print("\nReshaped array:\n", array2)
print("\nTransposed array:\n", array3)

Original array:
 [ 1  3  5  7  9 11]

Reshaped array:
 [[ 1  3  5]
 [ 7  9 11]]

Transposed array:
 [[ 1  7]
 [ 3  9]
 [ 5 11]]


NumPy Array Statistical Functions

In [7]:
marks = np.array([76, 78, 81, 66, 85])

meanMarks = np.mean(marks)
print("Mean:",meanMarks)

medianMarks = np.median(marks)
print("Median:",medianMarks)

minMarks = np.min(marks)
print("Minimum marks:", minMarks)

maxMarks = np.max(marks)
print("Maximum marks:", maxMarks)

Mean: 77.2
Median: 78.0
Minimum marks: 66
Maximum marks: 85
