Create a 2-D NumPy Array

In [4]:
import numpy as np
array1 = [
    [1,2,3,4,5,5],
    [11,221,121,12,1,1]
]
npArry = np.array(array1)
print(npArry)
print(f"Dimension: {npArry.ndim}")
print(f"Shape: {npArry.shape}")
print(f"Type: {type(npArry)}")

[[  1   2   3   4   5   5]
 [ 11 221 121  12   1   1]]
Dimension: 2
Shape: (2, 6)
Type: <class 'numpy.ndarray'>


Create a 3-D NumPy Array

In [7]:
array2 = [
    [
        [1,2,2,2,11,4],
        [0,9,4,5,21,2]
    ],
    [
        [33,12,12,4,3,11],
        [1,12,22,24,11,4],
        
    ]
]
npArray2 = np.array(array2)
print(npArray2)
print(f"Dimension: {npArray2.ndim}")
print(f"Shape: {npArray2.shape}")
print(f"Type: {type(npArray2)}")


[[[ 1  2  2  2 11  4]
  [ 0  9  4  5 21  2]]

 [[33 12 12  4  3 11]
  [ 1 12 22 24 11  4]]]
Dimension: 3
Shape: (2, 2, 6)
Type: <class 'numpy.ndarray'>


Create N-D Arrays using np.zeros()

In [18]:
npArrayZeros = np.zeros((2,2))
print("x---------FOR 2D ARRAY---------x")
print(npArrayZeros)
print(f"Dimension: {npArrayZeros.ndim}")
print(f"Shape: {npArrayZeros.shape}")
print(f"Type: {type(npArrayZeros)}")

print("x---------FOR 3D ARRAY---------x")
npArrayZeros2 = np.zeros((2,3,4))
print(npArrayZeros2)
print(f"Dimension: {npArrayZeros2.ndim}")
print(f"Shape: {npArrayZeros2.shape}")
print(f"Type: {type(npArrayZeros2)}")

x---------FOR 2D ARRAY---------x
[[0. 0.]
 [0. 0.]]
Dimension: 2
Shape: (2, 2)
Type: <class 'numpy.ndarray'>
x---------FOR 3D ARRAY---------x
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Dimension: 3
Shape: (2, 3, 4)
Type: <class 'numpy.ndarray'>


Create N-D Array with a Specified Value

In [19]:
npSpecified = np.full((2,2),7)
print("x---------FOR 2D ARRAY---------x")
print(npSpecified)
print(f"Dimension: {npSpecified.ndim}")
print(f"Shape: {npSpecified.shape}")
print(f"Type: {type(npSpecified)}")

print("x---------FOR 3D ARRAY---------x")
npSpecified2 = np.full((2,3,4),7)
print(npSpecified2)
print(f"Dimension: {npSpecified2.ndim}")
print(f"Shape: {npSpecified2.shape}")
print(f"Type: {type(npSpecified2)}")

x---------FOR 2D ARRAY---------x
[[7 7]
 [7 7]]
Dimension: 2
Shape: (2, 2)
Type: <class 'numpy.ndarray'>
x---------FOR 3D ARRAY---------x
[[[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]
Dimension: 3
Shape: (2, 3, 4)
Type: <class 'numpy.ndarray'>


Creating Arrays With np.random.rand()

In [22]:
npRandomRand = np.random.rand(2,2)
print("x---------FOR 2D ARRAY---------x")
print(npRandomRand)
print(f"Dimension: {npRandomRand.ndim}")
print(f"Shape: {npRandomRand.shape}")
print(f"Type: {type(npRandomRand)}")

print("x---------FOR 3D ARRAY---------x")
npRandomRand2 = np.random.rand(2,3,4)
print(npRandomRand2)
print(f"Dimension: {npRandomRand2.ndim}")
print(f"Shape: {npRandomRand2.shape}")
print(f"Type: {type(npRandomRand2)}")

x---------FOR 2D ARRAY---------x
[[0.43592005 0.91440695]
 [0.83840749 0.37557525]]
Dimension: 2
Shape: (2, 2)
Type: <class 'numpy.ndarray'>
x---------FOR 3D ARRAY---------x
[[[0.5125224  0.87715996 0.11209983 0.08335925]
  [0.51089997 0.07054255 0.00503384 0.66345555]
  [0.94054414 0.25845016 0.80507014 0.43205523]]

 [[0.11458789 0.08858065 0.09243801 0.93407013]
  [0.23382483 0.95755062 0.09528533 0.59805144]
  [0.14092077 0.89786506 0.27099461 0.21284333]]]
Dimension: 3
Shape: (2, 3, 4)
Type: <class 'numpy.ndarray'>


Create Empty N-D NumPy Array