NumPy Matrix Operations

In [3]:
import numpy as np


matrix1 = np.array([[1, 3], 
                   [5, 7]])

print("2x2 Matrix:\n",matrix1)

matrix2 = np.array([[2, 3, 5],
             	    [7, 14, 21],
                    [1, 3, 5]])
                    
print("\n3x3 Matrix:\n",matrix2)

2x2 Matrix:
 [[1 3]
 [5 7]]

3x3 Matrix:
 [[ 2  3  5]
 [ 7 14 21]
 [ 1  3  5]]


Perform Matrix Multiplication in NumPy

In [4]:

matrix1 = np.array([[1, 3], 
             		[5, 7]])
             
matrix2 = np.array([[2, 6], 
                    [4, 8]])

result = np.dot(matrix1, matrix2)

print("matrix1 x matrix2: \n",result)

matrix1 x matrix2: 
 [[14 30]
 [38 86]]


Transpose NumPy Matrix

In [8]:

matrix1 = np.array([[1, 3], 
             		[5, 7]])

result = np.transpose(matrix1)

print("Original: \n", matrix1)
print("Transpose: \n", result)


Original: 
 [[1 3]
 [5 7]]
Transpose: 
 [[1 5]
 [3 7]]


Calculate Inverse of a Matrix in NumPy

In [9]:

matrix1 = np.array([[1, 3, 5], 
             		[7, 9, 2],
                    [4, 6, 8]])

result = np.linalg.inv(matrix1)

print(result)

[[-1.11111111 -0.11111111  0.72222222]
 [ 0.88888889  0.22222222 -0.61111111]
 [-0.11111111 -0.11111111  0.22222222]]


Find Determinant of a Matrix in NumPy

In [10]:

matrix1 = np.array([[1, 2, 3], 
             		[4, 5, 1],
                    [2, 3, 4]])

result = np.linalg.det(matrix1)

print(result)

-5.000000000000001


Flatten Matrix in NumPy

In [12]:
matrix1 = np.array([[1, 2, 3], 
             		[4, 5, 7]])

result = matrix1.flatten()
print("Flattened 2x3 matrix:", result)

Flattened 2x3 matrix: [1 2 3 4 5 7]
