NumPy Array Slicing

1D NumPy Array Slicing

In [17]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])
print(f"Intially till 1 to 4 element: {array1[0:4]}") #last one is ignored
print(f"Intially till 4 to last element: {array1[3:len(array1)]} ")


Intially till 1 to 4 element: [1 3 5 7]
Intially till 4 to last element: [7 8 9 2 4 6] 


In [18]:
array1

array([1, 3, 5, 7, 8, 9, 2, 4, 6])

Using start Parameter

In [19]:
print(array1[5:])

[9 2 4 6]


In [20]:
array1[5:] = 7
print(array1)

[1 3 5 7 8 7 7 7 7]


In [21]:
array2 = np.array([1, 3, 5, 17, 18, 19, 12, 14, 6])

Using stop Parameter

In [23]:
print(array2[:5])

[ 1  3  5 17 18]


In [24]:
array2[: 5] = 7

In [25]:
print(array2)

[ 7  7  7  7  7 19 12 14  6]


In [27]:
array3 = np.array([11, 31, 15, 71, 181, 191, 102, 14, 6])

Using start and stop parameter

In [28]:
print(array3[2:5])

[ 15  71 181]


In [29]:
array3[2:5] = 7
print(array3)

[ 11  31   7   7   7 191 102  14   6]


Using start, stop, and step parameter

In [30]:
array4 = np.array([2, 4, 6, 8, 10, 12])

array4[1:5:2] = 16
print(array4)

[ 2 16  6 16 10 12]


NumPy Array Negative Slicing

In [31]:

numbers = np.array([2, 4, 6, 8, 10, 12])

print(numbers[-3:])    # [8 10 12]

print(numbers[-5:-2])    # [4 6 8] 

print(numbers[-1::-2])   # [12 8 4]

[ 8 10 12]
[4 6 8]
[12  8  4]


Reverse NumPy Array Using Negative Slicing

In [32]:

numbers = np.array([2, 4, 6, 8, 10, 12])

reversed_numbers = numbers[::-1]
print(reversed_numbers)

# Output: [12 10 8 6 4 2]

[12 10  8  6  4  2]


2D NumPy Array Slicing

In [40]:
# create a 2D array
npArr2D = np.array([[1, 3, 5, 7], 
                   [9, 11, 13, 15],
                   [1, 3, 5, 7], 
                   [9, 11, 13, 15]])
print(npArr2D)

[[ 1  3  5  7]
 [ 9 11 13 15]
 [ 1  3  5  7]
 [ 9 11 13 15]]


In [41]:
print(npArr2D[:,3]) #columns and row

[ 7 15  7 15]


In [46]:
npArr2D[0:2,0:2]

array([[ 1,  3],
       [ 9, 11]])

In [47]:
npArr2D[:2,:2]

array([[ 1,  3],
       [ 9, 11]])

In [43]:
npArr2D[0:4:2,0:4:2]

array([[1, 5],
       [1, 5]])