NumPy Boolean Indexing

Boolean Masks in NumPy

1D Boolean Indexing in NumPy

In [2]:
import numpy as np


array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

boolMask = array1 % 2 != 0


result = array1[boolMask]

print(result)


[1 3 5 7 9]


In [3]:
array2 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])
boolMask2 = (array2 < 10) | (array2 > 40)
result2 = array2[boolMask2]
print(result2)

[ 1  2  4  9 47 51 52]


Modify Elements Using Boolean Indexing

In [11]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
numbers2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

boolMask = numbers % 2 == 0
print(boolMask)
numbers[boolMask] = 0 # Effect occur on the main data of number now all numbers are modified
print(numbers)

#  so better approach is to do with the copy of the data so your original data couldn't change
copyNumbers = numbers2.copy()
copyBoolMask = copyNumbers % 2 == 0
copyNumbers[copyBoolMask] = 0
print(copyNumbers)
print(numbers2)

[False  True False  True False  True False  True False  True]
[1 0 3 0 5 0 7 0 9 0]
[1 0 3 0 5 0 7 0 9 0]
[ 1  2  3  4  5  6  7  8  9 10]


2D Boolean Indexing in NumPy

In [21]:
array1 = np.array([[1, 7, 9], 
                    [14, 19, 21], 
                    [25, 29, 35]])

boolean_mask = array1 > 9

result = array1[boolean_mask]
# print(array1[1,:])
print(result)

[14 19 21 25 29 35]


We then use this boolean mask to index array1, which returns a flattened 1D array containing only the elements that satisfy the condition.