Numpy is a python library created at 2005 that perform numericl calculation, it is generally used for working with an array.

Why we use numpy?

In python we use list to work with the array but when it comes to large operation python list are not enough optimized. Numpy Array are 50X faster than a python list and its used in complex mathematical and statistical operation

In [2]:
import numpy as np

In [6]:
array1 = [1,2,3,44,5,1]
print(type(array1))

<class 'list'>


In [7]:
npArray = np.array(array1)
print(type(npArray))

<class 'numpy.ndarray'>


Create an Array Using np.zeros()

In [8]:
npZeros = np.zeros(5)
print(npZeros)

[0. 0. 0. 0. 0.]


In [13]:
npZeros.ndim

1

In [19]:
npZeros2 = np.zeros((2,3))
print(npZeros2)
print(f"Dimension: {npZeros.ndim}")

[[0. 0. 0.]
 [0. 0. 0.]]
Dimension: 2


Create an Array With np.arange()

In [20]:
npArange = np.arange(10)
print(npArange)
print(f"Dimension: {npArange.ndim}")

[0 1 2 3 4 5 6 7 8 9]
Dimension: 1


In [26]:
npArange = np.arange(10).reshape(5,2)
print(npArange)
print(f"Dimension: {npArange.ndim}")
print(f"Dimension: {npArange.shape}")

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Dimension: 2
Dimension: (5, 2)


Create an Array With np.random.rand()

In [28]:
npRandomRand = np.random.rand(5)
print(npRandomRand)
print(f"Dimension: {npRandomRand.ndim}")


[0.90774113 0.14160678 0.18244622 0.98123989 0.47761237]
Dimension: 1


In [32]:
npRandomRand = np.random.rand(2,3)
print(npRandomRand)
print(f"Dimension: {npRandomRand.ndim}")


[[0.64399381 0.00434706 0.78205508]
 [0.28306143 0.44948534 0.21430465]]
Dimension: 2


Create an Empty NumPy Array

In [33]:
npEmpty = np.empty(4)
print(npEmpty)
print(f"Dimension: {npEmpty.ndim}")

[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56607956e-307]
Dimension: 1


In [34]:
npEmpty = np.empty((2,3))
print(npEmpty)
print(f"Dimension: {npEmpty.ndim}")

[[0.64399381 0.00434706 0.78205508]
 [0.28306143 0.44948534 0.21430465]]
Dimension: 2
