NumPy Fancy Indexing

In [3]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

selectedNum = array1[[1, 2, 5, 7]]

print(selectedNum)


[2 3 6 8]


In [4]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# select a single element
ind = array1[3]

print("Simple Indexing:",ind)  

# select multiple elements
fancyInd = array1[[1, 2, 5, 7]]

print("Fancy Indexing:",fancyInd)   

Simple Indexing: 4
Fancy Indexing: [2 3 6 8]


Fancy Indexing for Sorting NumPy Array

In [5]:
import numpy as np

array1 = np.array([3, 2, 6, 1, 8, 5, 7, 4])
indices = [1, 3, 6]
new_values = [10, 20, 30]

array1[indices] = new_values

print(array1)



[ 3 10  6 20  8  5 30  4]


In [11]:
import numpy as np

# create a 2D array
array1 = np.array([[1, 3, 5], 
                [11, 7, 9], 
                [13, 18, 29]])

row_indices = np.array([0, 2])
selected_rows = array1[row_indices,:]
selected_cols = array1[:,row_indices]

print(selected_rows)
print(selected_cols)

[[ 1  3  5]
 [13 18 29]]
[[ 1  5]
 [11  9]
 [13 29]]
