NumPy Set Operations

Set Union Operation in NumPy

In [5]:
import numpy as np

A = np.array([1, 3, 5])
B = np.array([0, 2, 3])


result = np.union1d(A, B)

print(result)  


[0 1 2 3 5]


Set Intersection Operation in NumPy

In [6]:
A = np.array([1, 3, 5])
B = np.array([0, 2, 3])


result = np.intersect1d(A, B)

print(result)  


[3]


Set Difference Operation in NumPy

In [9]:
A = np.array([1, 3, 5])
B = np.array([0, 2, 3])

result = np.setdiff1d(A, B)

print(result)  


[1 5]


Set Symmetric Difference Operation in NumPy

In [12]:
A = np.array([1, 3, 5])
B = np.array([0, 2, 3])

result = np.setxor1d(A, B)

print(result)  


[0 1 2 5]


Unique Values From a NumPy Array

In [13]:
array1 = np.array([1,1, 2, 2, 4, 7, 7, 3, 5, 2, 5])


result = np.unique(array1)

print(result)  


[1 2 3 4 5 7]
