A data type is a way to specify the type of data that will be stored in an array.

In [8]:
import numpy as np
npArr = np.array([2, 4, 6])
print(npArr)
print(f"Dimension: {npArr.ndim}")
print(f"Shape: {npArr.shape}")
print(f"Type: {type(npArr)}")
print(f"Data Type: {npArr.dtype}")


[2 4 6]
Dimension: 1
Shape: (3,)
Type: <class 'numpy.ndarray'>
Data Type: int64


In [9]:
# create an array of integer numbers
intArr = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
floatArr = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complexArr = np.array([1+2j, 2+3j, 3+4j])

# check the data type of int_array
print(intArr.dtype)  # prints int64

# check the data type of float_array
print(floatArr.dtype)  # prints float64

# check the data type of complex_array
print(complexArr.dtype)  # prints complex128

int64
float64
complex128


create an array of 32-bit integers

In [11]:
array1 = np.array([1, 3, 7], dtype='int32')

print(array1, array1.dtype)

[1 3 7] int32


Creating NumPy Arrays With a Defined Data Type

In [12]:
# create an array of 8-bit integers
array1 = np.array([1, 3, 7], dtype='int8')

# create an array of unsigned 16-bit integers
array2 = np.array([2, 4, 6], dtype='uint16')

# create an array of 32-bit floating-point numbers
array3 = np.array([1.2, 2.3, 3.4], dtype='float32')

# create an array of 64-bit complex numbers
array4 = np.array([1+2j, 2+3j, 3+4j], dtype='complex64')

# print the arrays and their data types
print(array1, array1.dtype)
print(array2, array2.dtype)
print(array3, array3.dtype)
print(array4, array4.dtype)

[1 3 7] int8
[2 4 6] uint16
[1.2 2.3 3.4] float32
[1.+2.j 2.+3.j 3.+4.j] complex64


NumPy Type Conversion

In [16]:
intArray = np.array([1, 3, 5, 7])
floatArray = intArray.astype("float") #float32, float64  but default 64
print(f"Data Type of intArray: {intArray.dtype}")
print(f"Data Type of floatArray: {floatArray.dtype}")

Data Type of intArray: int64
Data Type of floatArray: float64
