Advance Numpy Operations

In [7]:
import numpy as np


array1 = np.array([1, 2, 3])
array2 = np.array([[1], [2], [3]])

sum = array1 + array2

print(sum)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


Compatibility Rules for Broadcasting

In [21]:

array1 = np.array([1, 2, 3])
array2 = np.array([[1,3,4], 
                   [2,5,5], 
                   [1,4,3],
                   [1,4,3]
                  ])
number = 5

sum = array1 + number
print(array2.shape)
print(array1.shape)
print(array1 + array2)
print(sum)

(4, 3)
(3,)
[[2 5 7]
 [3 7 8]
 [2 6 6]
 [2 6 6]]
[6 7 8]
