Numpy Random

In [2]:
import numpy as np

randomNumber = np.random.randint(0, 10)

print(randomNumber)


3


In [4]:
randomFloat = np.random.rand()
print(randomFloat)

0.915227302714655


In [19]:

array1D = np.random.randint(0, 10 , 5)
array2D = np.random.randint(0, 10 , size=(2,2))

print("1D Random Integer Array:\n",array1D)
print("2D Random Integer Array:\n",array2D)

floatArray = np.random.rand(4) #.reshape(2,2) for 2D
print(floatArray)

# generate 2D array of shape (3, 4) with random integers
result = np.random.randint(0, 10, (3,4))
print("\n2D Random Integer Array:\n",result)


1D Random Integer Array:
 [5 9 6 8 7]
2D Random Integer Array:
 [[4 6]
 [3 3]]
[0.45637188 0.24015979 0.21053397 0.09992187]

2D Random Integer Array:
 [[7 2 4 1]
 [7 5 9 0]
 [9 6 0 6]]


Choose Random Number from NumPy Array

In [22]:
# create an array of integers from 1 to 5
array1 = np.array([1, 2, 3, 4, 5])
randomChoice = np.random.choice(array1)

print(randomChoice)



2
