NumPy Linear Algebra Functions

NumPy dot() Function

In [3]:
import numpy as np

array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])
result = np.dot(array1, array2)

print(result)


44


NumPy inner() Function

In [5]:
array1 = np.array([[1, 3], 
                   [5, 7]])
array2 = np.array([[2, 4], 
                   [6, 8]])
result = np.inner(array1, array2)
print(result)

[[14 30]
 [38 86]]


NumPy outer() Function

In [6]:
import numpy as np

array1 = np.array([1, 3, 5])
array2 = np.array([2, 4, 6])
result = np.outer(array1, array2)

print(result)

[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]


NumPy det() Function

In [14]:
array1 = np.array([[1, 3], 
                  [5, 7]])
result = np.linalg.det(array1)
print(result)


-7.999999999999998


NumPy trace() Function

In [15]:
array1 = np.array([[5, 3, 5], 
                   [9, 2, 1], 
                   [7, 8, 10]])
result = np.trace(array1)
print(result)


17


NumPy inv() Function

In [16]:
import numpy as np

array1 = np.array([[2, 4], 
                  [6, 8]])
result = np.linalg.inv(array1)
print(result)

[[-1.    0.5 ]
 [ 0.75 -0.25]]
