# **NUMPY**

# **November 06, 2025 Donnerstag 00:18**

***These 50 problems cover almost every NumPy concept needed for data analytics, data science, and interviews:***

**Easy**: Basics, creation, simple operations

**Medium**: Indexing, slicing, stacking, statistics

**Hard**: Linear algebra, broadcasting, advanced operations

**Hardest**: Real-world datasets, probability, distance metrics, normalization

# **EASY (1–15) – Basics of NumPy**

***Note: I will import numpy for each task so don't think akward or something else why i am using mulitiple time***

**1.	Create a 1D array of numbers from 0 to 9.**

In [19]:
import numpy as np
npArray = np.arange(10)
print(f"Numpy Array: {npArray}")
print(f"Numpy Array Dimension: {npArray.ndim}")


Numpy Array: [0 1 2 3 4 5 6 7 8 9]
Numpy Array Dimension: 1


**2. Create a 3×3 matrix filled with zeros.**

In [13]:
import numpy as np
npZeros = np.zeros((3,3))
print(f"Numpy Zeros Array: \n {npZeros}")
print(f"Numpy Zeros Array Dimension: {npZeros.shape}")

Numpy Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Numpy Array Dimension: (3, 3)


**3.	Create a 2×3 matrix filled with ones.**

In [15]:
import numpy as np
npOnes = np.ones((2,3))
print(f"Numpy Ones Array: \n {npOnes}")
print(f"Numpy Ones Array Dimension: {npOnes.shape}")

Numpy Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Numpy Ones Array Dimension: (2, 3)


**4.	Generate an array of 10 random numbers between 0 and 1.**

In [17]:
import numpy as np
rand = np.random.rand(10)
print(f"Random Between 0 to 1: \n {rand}")

Random Between 0 to 1: 
 [0.36952582 0.10828283 0.45257875 0.13176197 0.72210152 0.56146217
 0.35181388 0.92351012 0.38123495 0.13743136]


**5.	Create a 1D array of numbers from 10 to 50 with a step of 5.**

In [21]:
import numpy as np
npStepJump = np.arange(10,50,5)
print(f"Number From 10 to 50 with the Jump of 5: \n {npStepJump}")

Number From 10 to 50 with the Jump of 5: 
 [10 15 20 25 30 35 40 45]


**6.	Find the shape, size, and data type of a given array.**

In [23]:
givenArray = [1,23,12,14,15,16,16,17]
npArr = np.array(givenArray)
print(f"Shape: {npArr.shape}")
print(f"Size: {npArr.size}")
print(f"DataType: {npArr.dtype}")

Shape: (8,)
Size: 8
DataType: int64


**7.	Convert a Python list [1,2,3,4] into a NumPy array.**

In [25]:
import numpy as np
myList = [1,2,3,4,5]
npArrays = np.array(myList)
print(f"Numpy Array: \n{npArrays}")
print(f"Data Type: {type(npArrays)}")


Numpy Array: 
[1 2 3 4 5]
Data Type: <class 'numpy.ndarray'>


**8.	Reshape a 1D array of 12 elements into a 3×4 array.**

In [29]:
import numpy as np
zwölfElement = np.arange(12)
print(f"1D Array: \n{zwölfElement}")
print(f"3x4 Converted Array: \n{zwölfElement.reshape(3,4)}")

1D Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 Converted Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**9.	Create a 5×5 identity matrix.**

In [36]:
import numpy as np
identityMatrix = np.identity(5)
print(identityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**10.	Create an array of 10 equally spaced numbers between 0 and 1.**

In [39]:
import numpy as np

equalSpace = np.linspace(0,1,10)
print(f"Eqaul Space 0 to 1: \n{equalSpace}")

Eqaul Space 0 to 1: 
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**11.	Extract the first 3 rows of a 5×5 random matrix.**

In [48]:
import numpy as np
randArr = np.round(np.random.rand(5,5)*100)
print(f"Random Array Of 5x5: \n{randArr}")
print(f"First 3 Row: \n{randArr[:3]}")

Random Array Of 5x5: 
[[79. 87. 78.  3. 51.]
 [35. 81. 53. 97. 98.]
 [51. 34. 95. 29. 47.]
 [42. 88. 72. 99. 49.]
 [91. 87. 76. 15. 84.]]
First 3 Row: 
[[79. 87. 78.  3. 51.]
 [35. 81. 53. 97. 98.]
 [51. 34. 95. 29. 47.]]


**12.	Replace all negative numbers in an array with zero.**

In [4]:
import numpy as np
listing = [1,2,4,5,6,78,-9,-3,34]
npList = np.array(listing)
print(f"Original Array: \n{npList}")
npList[npList < 0] = 0
print(f"After Mask: \n{npList}")


Original Array: 
[ 1  2  4  5  6 78 -9 -3 34]
After Mask: 
[ 1  2  4  5  6 78  0  0 34]


**13.	Multiply two arrays element-wise.**

In [10]:
import numpy as np
listing1 = [1,2,4,45,26,78,9,34]
listing2 = [1,2,4,63,18,19,113,3]
npList1 = np.array(listing1)
npList2 = np.array(listing2)
print(f"Original List1: \n{npList1}")
print(f"Original List2: \n{npList2}")

print("x----------------------------------x")

#Approach # 01 - With * sign
multApproach1 = npList1 * npList2
#Approach # 02 - With multiply funciton
multApproach2 = np.multiply(npList1,npList2)

print(f"Approach # 01: \n{multApproach1}")
print(f"Approach # 02: \n{multApproach2}")



Original List1: 
[ 1  2  4 45 26 78  9 34]
Original List2: 
[  1   2   4  63  18  19 113   3]
x----------------------------------x
Approach # 01: 
[   1    4   16 2835  468 1482 1017  102]
Approach # 02: 
[   1    4   16 2835  468 1482 1017  102]


**14.	Find the sum, mean, and standard deviation of a 1D array.**

In [17]:
import numpy as np
oneDimArray = [1,2,3,5,6,71,123,13,13,2,3,32,21,34]
npOneDim = np.array(oneDimArray)
print(f"Original Array:\n{npOneDim}")
print(f"Sum: {np.sum(npOneDim)}")
print(f"Mean: {np.mean(npOneDim)}")
print(f"Median: {np.median(npOneDim)}")
print(f"Min: {np.min(npOneDim)}")
print(f"Max: {np.max(npOneDim)}")
print(f"Standard Deviation: {np.std(npOneDim)}")

Original Array:
[  1   2   3   5   6  71 123  13  13   2   3  32  21  34]
Sum: 329
Mean: 23.5
Median: 9.5
Min: 1
Max: 123
Standard Deviation: 33.258189109708646


**15.	Flatten a 2D array into a 1D array.**

In [24]:
import numpy as np
twoDim = [
    [1,2,4,5,67,77,1],
    [1,2,4,5,67,77,1],
]
npTwoDim = np.array(twoDim)
print(f"Original Array:\n {npTwoDim}")
print(f"Flatten Array:\n {npTwoDim.flatten()}")


Original Array:
 [[ 1  2  4  5 67 77  1]
 [ 1  2  4  5 67 77  1]]
Flatten Array:
 [ 1  2  4  5 67 77  1  1  2  4  5 67 77  1]


# **MEDIUM (16–30) – Indexing, slicing, statistics, and operations**

**16.	Create a 10×10 array and find the minimum and maximum values.**

In [29]:
import numpy as np


npArr = np.random.random((10,10))
npArrMin = npArr.min()
npArrMax = npArr.max()
print(f"Random 10x10 array: \n{npArr}")
print(f"Shape: {npArr.shape}")
print(f"Min: {npArrMin}")
print(f"Max: {npArrMax}")
print(f"Flatten: {npArr.flatten()}")
print(f"Index Of Max: {npArr.flatten().argmax()}")

Random 10x10 array: 
[[0.47474632 0.88840235 0.72961883 0.43793514 0.27843288 0.23535856
  0.11142874 0.11591238 0.21233406 0.31304746]
 [0.91040046 0.12826878 0.38236492 0.19559151 0.73143114 0.65717567
  0.61544193 0.93459098 0.38748484 0.68980883]
 [0.42353822 0.74791073 0.48946023 0.28867107 0.12849935 0.87325959
  0.7613402  0.51558476 0.20696841 0.22543464]
 [0.45749094 0.94930667 0.30780646 0.26262145 0.40373235 0.54237122
  0.33893942 0.47782441 0.24047655 0.49647516]
 [0.02309437 0.46496083 0.00315797 0.60310357 0.42703948 0.26355962
  0.53350404 0.87263927 0.96216164 0.02399904]
 [0.33607862 0.06524968 0.12444146 0.61577158 0.49684655 0.23835805
  0.16738372 0.53045679 0.41791225 0.47823439]
 [0.54734981 0.21709589 0.62054663 0.25682447 0.28792092 0.12465883
  0.94153669 0.38372682 0.2997691  0.27306619]
 [0.90908839 0.67111095 0.59162182 0.10658771 0.26456486 0.26419529
  0.95790533 0.14262247 0.34774017 0.85846892]
 [0.07883369 0.53480976 0.73840354 0.54978538 0.01642581 0.

**17.	Select all odd numbers from a 1D array of 1–20.**

In [47]:
import numpy as np
import random
num = np.random.randint(1, 20, size=20)  # 1 to 20
odd = num[num%2 !=0]
print(f"Original: {num}")
print(f"Odd: {odd}")


Original: [19  7 14 18 15 17 14  5  4  8  4 19  1  7 16 11  1  2  4 13]
Odd: [19  7 15 17  5 19  1  7 11  1 13]


**18.	Reverse a 1D array.**

In [58]:
import numpy as np
import random
oneDimNp= np.random.randint(1, 20, size=10)  # 1 to 10
print(f"Original: {oneDimNp}")
# Approach 1:
reversed = np.flip(oneDimNp)
print(f"Approach 1 - Reversed: {reversed}")
# Approach 2:
rev = oneDimNp[::-1]
print(f"Approach 2 - Reversed: {rev}")

Original: [12  7  9  6 13 15  9  5  3 10]
Approach 1 - Reversed: [10  3  5  9 15 13  6  9  7 12]
Approach 2 - Reversed: [10  3  5  9 15 13  6  9  7 12]


**19.	Extract a submatrix (2×2) from a 4×4 matrix.**

In [71]:
import numpy as np
npOriginal = np.arange(16).reshape(4,4)
print(f"Original: \n{npOriginal}")
print(f"Original Matrix Shape: {npOriginal.shape}")
subMatrix = npOriginal[0:2,0:2]
print(f"SubMatrix: \n{subMatrix}")
print(f"Sub Matrix Shape: {subMatrix.shape}")


Original: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Original Matrix Shape: (4, 4)
SubMatrix: 
[[0 1]
 [4 5]]
Sub Matrix Shape: (2, 2)


**20.	Stack two arrays vertically and horizontally.**

In [86]:
import numpy as np
numpyArr = np.arange(16).reshape(4,4)
numpyArr2 = np.arange(16,32).reshape(4,4)
print(f"Array1: \n{numpyArr}")
print(f"Array2: \n{numpyArr2}")
horizStack = np.hstack([numpyArr, numpyArr2])
print(f"Horizontal Stack: \n{horizStack}")
verStack = np.vstack([numpyArr, numpyArr2])
print(f"Vertical Stack: \n{verStack}")

Array1: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Array2: 
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Horizontal Stack: 
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]
Vertical Stack: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


**21.	Create a 1D array of 15 random integers from 0 to 100 and sort it.**

In [95]:
import numpy as np
rand = np.random.randint(0,100, size=15)
print(f"Original: {rand}")
print(f"Sorted: {np.sort(rand)}")

Original: [82 72 86 15 89 51 24 49 90 38  9 94 44 47 19]
Sorted: [ 9 15 19 24 38 44 47 49 51 72 82 86 89 90 94]


**22.	Compute the dot product of two 2×2 matrices.**

In [110]:
import numpy as np
arr1 = np.arange(1,8,2).reshape(2,2)
arr2 = np.arange(1,5).reshape(2,2)

print(f"matrix 1: \n{arr1}")
print(f"matrix 2: \n{arr2}")
print(f"Dot Product: \n{np.dot(arr1,arr2)}")

matrix 1: 
[[1 3]
 [5 7]]
matrix 2: 
[[1 2]
 [3 4]]
Dot Product: 
[[10 14]
 [26 38]]


**23.	Find the unique elements and their counts in an array.**

In [116]:
import numpy as np

arr = np.array([[1, 2, 2],
                [3, 5, 1],
                [4, 2, 1]])
# Get unique elements and their counts
unique_vals, counts = np.unique(arr, return_counts=True)
print(unique_vals)
print(counts)

[1 2 3 4 5]
[3 3 1 1 1]


**24.	Normalize a 1D array to have values between 0 and 1.**

In [122]:
import numpy as np

arr = np.array([100, 20, 30, 410, 501])

# Min-max normalization
normalized = (arr - arr.min()) / (arr.max() - arr.min())

print("Original array:", arr)
print("Normalized array:", normalized)

# Z-score normalization
mean = arr.mean()
std = arr.std()

standard_normalized = (arr - mean) / std

print("Original array:", arr)
print("Mean:", mean)
print("Std Dev:", std)
print("Z-score Normalized:", standard_normalized)



Original array: [100  20  30 410 501]
Normalized array: [0.16632017 0.         0.02079002 0.81081081 1.        ]
Original array: [100  20  30 410 501]
Mean: 212.2
Std Dev: 202.6113521005178
Z-score Normalized: [-0.55376956 -0.94861417 -0.8992586   0.97625329  1.42538904]


***Extra: Normalization for 2D Array:***

In [128]:
import numpy as np
arr = np.array([
    [10, 20, 30],
    [5, 15, 40],
    [25, 35, 45]
])

min = arr.min()
max = arr.max()
print(arr)
print(f"Min: {min} & Max: {max}")

nor = (arr-min) / (max-min)
print(nor)

rowMin = arr.min(axis=1, keepdims=True)
rowMax = arr.max(axis=1, keepdims=True)

print(f"Row Min: {rowMin} & Row Max: {rowMax}")

rowNor = (arr-rowMin) / (rowMax-rowMin)
print(f"Row Wise Normalization: {rowNor}")
#same with col but axis = 0



[[10 20 30]
 [ 5 15 40]
 [25 35 45]]
Min: 5 & Max: 45
[[0.125 0.375 0.625]
 [0.    0.25  0.875]
 [0.5   0.75  1.   ]]
Row Min: [[10]
 [ 5]
 [25]] & Row Max: [[30]
 [40]
 [45]]
Row Wise Normalization: [[0.         0.5        1.        ]
 [0.         0.28571429 1.        ]
 [0.         0.5        1.        ]]


**25.	Compute the cumulative sum of a 1D array.**

In [135]:
import numpy as np
arr = np.random.randint(1,10, size=4)
print(f"Original: {arr}")
print(f"Comulative Sum: {np.cumsum(arr)}")

Original: [6 5 8 3]
Comulative Sum: [ 6 11 19 22]


***Extra: by manual python:***

In [2]:
import random
import numpy as np
arr = [1,3,4,6,6,10,20,5,5,4,3,2,1]
def myCumSum(yourArr):
  arr = np.array(yourArr)
  cumsum =  []
  sum = 0
  for i in range(len(arr)):
    if i == 0:
      sum = arr[i]
      cumsum.append(arr[i])
    else:
      sum = sum + arr[i]
      cumsum.append(sum)
  return np.array(cumsum)

myCumSum(arr)


array([ 1,  4,  8, 14, 20, 30, 50, 55, 60, 64, 67, 69, 70])

**26.	Create a boolean mask to select elements greater than 5 from an array.**

In [10]:
import numpy as np
arr = np.random.randint(1,10, size=10)
print(f"Original: {arr}")
maskArr = arr>5
filterArr = arr[maskArr]
print(f"Boolen Mask Greater than 5: {maskArr}")
print(f"Filtered: {filterArr}")

Original: [7 5 4 8 7 2 4 3 2 4]
Boolen Mask Greater than 5: [ True False False  True  True False False False False False]
Filtered: [7 8 7]


***Extra: Boolean Masking of Rows and Columns***

In [49]:
import numpy as np

arr = np.random.randint(1, 7, size=(4, 4))
print(f"Original: \n{arr}")
maskRow = (arr>5).any(axis=1)

print("x-----------------x")

#for rows:
print(f"Mask Row: {maskRow}")
filterRow = arr[maskRow,:]
print(f"Filter Row: \n{filterRow}")

print("x-----------------x")

#for columns:
maskCol = (arr>5).any(axis=0)
print(f"Mask Columns: {maskCol}")
filterCol = arr[:,maskCol]
print(f"Filter Columns: \n{filterCol}")



Original: 
[[3 6 1 5]
 [4 5 5 5]
 [5 5 1 1]
 [6 3 2 5]]
x-----------------x
Mask Row: [ True False False  True]
Filter Row: 
[[3 6 1 5]
 [6 3 2 5]]
x-----------------x
Mask Columns: [ True  True False False]
Filter Columns: 
[[3 6]
 [4 5]
 [5 5]
 [6 3]]


**27.	Replace all odd numbers in an array with -1.**

In [52]:
import numpy as np
npArr = np.arange(1,11)
print(f"Original: {npArr}")
npArr[npArr%2==0] = -1
print(f"Odd Replaced: {npArr}")

Original: [ 1  2  3  4  5  6  7  8  9 10]
Odd Replaced: [ 1 -1  3 -1  5 -1  7 -1  9 -1]


**28.	Compute row-wise and column-wise sum of a 3×4 matrix.**

In [65]:
import numpy as np
npArr2 = np.random.randint(1,5, size=(3,4))
print(f"Original: \n{npArr2}")

print("x-------------x")

rowSum = np.sum(npArr2,axis=1)
print(f"Row Sum: {rowSum}")

print("x-------------x")
colSum = np.sum(npArr2,axis=0)
print(f"Columns Sum: {colSum}")

Original: 
[[2 3 3 4]
 [2 1 4 3]
 [4 3 4 3]]
x-------------x
Row Sum: [12 10 14]
x-------------x
Columns Sum: [ 8  7 11 10]


**29.	Create a 3×3 matrix and compute its transpose.**

In [73]:
import numpy as np
# print(np.zeros((3,3), dtype=np.int32))
npArr3 = np.random.randint(1,19, size=(3,3))
print(f"Original:\n{npArr3}")
print("x--------------x")
transpose = np.transpose(npArr3)
print(f"Transpose: \n{transpose}")

Original:
[[ 3  8  5]
 [ 3 13  4]
 [15 18 18]]
x--------------x
Transpose: 
[[ 3  3 15]
 [ 8 13 18]
 [ 5  4 18]]


**30.	Perform element-wise square and square-root operations on an array.**

In [86]:
import numpy as np
npArr1D = np.arange(2,7)
print(f"1D Array Original: {npArr1D}")
sq1D = np.square(npArr1D)
print(f"Square of 1D: {sq1D}")
sqrt1D = np.sqrt(npArr1D)
print(f"Square Root of 1D: \n{sqrt1D}")
print("x---------------------x")

npArr2D = np.random.randint(1,7, size=(2,2))
print(f"2D Array Original: \n{npArr2D}")
sq2D = np.square(npArr2D)
print(f"Square of 2D: \n{sq2D}")
sqrt2D = np.sqrt(npArr2D)
print(f"Square Root of 2D: \n{sqrt2D}")


1D Array Original: [2 3 4 5 6]
Square of 1D: [ 4  9 16 25 36]
Square Root of 1D: 
[1.41421356 1.73205081 2.         2.23606798 2.44948974]
x---------------------x
2D Array Original: 
[[5 1]
 [4 4]]
Square of 2D: 
[[25  1]
 [16 16]]
Square Root of 2D: 
[[2.23606798 1.        ]
 [2.         2.        ]]
