# **NUMPY**

# **November 06, 2025 Donnerstag 00:18**

***These 50 problems cover almost every NumPy concept needed for data analytics, data science, and interviews:***

**Easy**: Basics, creation, simple operations

**Medium**: Indexing, slicing, stacking, statistics

**Hard**: Linear algebra, broadcasting, advanced operations

**Hardest**: Real-world datasets, probability, distance metrics, normalization

# **EASY (1–15) – Basics of NumPy**

***Note: I will import numpy for each task so don't think akward or something else why i am using mulitiple time***

**1.	Create a 1D array of numbers from 0 to 9.**

In [19]:
import numpy as np
npArray = np.arange(10)
print(f"Numpy Array: {npArray}")
print(f"Numpy Array Dimension: {npArray.ndim}")


Numpy Array: [0 1 2 3 4 5 6 7 8 9]
Numpy Array Dimension: 1


**2. Create a 3×3 matrix filled with zeros.**

In [13]:
import numpy as np
npZeros = np.zeros((3,3))
print(f"Numpy Zeros Array: \n {npZeros}")
print(f"Numpy Zeros Array Dimension: {npZeros.shape}")

Numpy Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Numpy Array Dimension: (3, 3)


**3.	Create a 2×3 matrix filled with ones.**

In [15]:
import numpy as np
npOnes = np.ones((2,3))
print(f"Numpy Ones Array: \n {npOnes}")
print(f"Numpy Ones Array Dimension: {npOnes.shape}")

Numpy Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Numpy Ones Array Dimension: (2, 3)


**4.	Generate an array of 10 random numbers between 0 and 1.**

In [17]:
import numpy as np
rand = np.random.rand(10)
print(f"Random Between 0 to 1: \n {rand}")

Random Between 0 to 1: 
 [0.36952582 0.10828283 0.45257875 0.13176197 0.72210152 0.56146217
 0.35181388 0.92351012 0.38123495 0.13743136]


**5.	Create a 1D array of numbers from 10 to 50 with a step of 5.**

In [21]:
import numpy as np
npStepJump = np.arange(10,50,5)
print(f"Number From 10 to 50 with the Jump of 5: \n {npStepJump}")

Number From 10 to 50 with the Jump of 5: 
 [10 15 20 25 30 35 40 45]


**6.	Find the shape, size, and data type of a given array.**

In [23]:
givenArray = [1,23,12,14,15,16,16,17]
npArr = np.array(givenArray)
print(f"Shape: {npArr.shape}")
print(f"Size: {npArr.size}")
print(f"DataType: {npArr.dtype}")

Shape: (8,)
Size: 8
DataType: int64


**7.	Convert a Python list [1,2,3,4] into a NumPy array.**

In [25]:
import numpy as np
myList = [1,2,3,4,5]
npArrays = np.array(myList)
print(f"Numpy Array: \n{npArrays}")
print(f"Data Type: {type(npArrays)}")


Numpy Array: 
[1 2 3 4 5]
Data Type: <class 'numpy.ndarray'>


**8.	Reshape a 1D array of 12 elements into a 3×4 array.**

In [29]:
import numpy as np
zwölfElement = np.arange(12)
print(f"1D Array: \n{zwölfElement}")
print(f"3x4 Converted Array: \n{zwölfElement.reshape(3,4)}")

1D Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 Converted Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**9.	Create a 5×5 identity matrix.**

In [36]:
import numpy as np
identityMatrix = np.identity(5)
print(identityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**10.	Create an array of 10 equally spaced numbers between 0 and 1.**

In [39]:
import numpy as np

equalSpace = np.linspace(0,1,10)
print(f"Eqaul Space 0 to 1: \n{equalSpace}")

Eqaul Space 0 to 1: 
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


**11.	Extract the first 3 rows of a 5×5 random matrix.**

In [48]:
import numpy as np
randArr = np.round(np.random.rand(5,5)*100)
print(f"Random Array Of 5x5: \n{randArr}")
print(f"First 3 Row: \n{randArr[:3]}")

Random Array Of 5x5: 
[[79. 87. 78.  3. 51.]
 [35. 81. 53. 97. 98.]
 [51. 34. 95. 29. 47.]
 [42. 88. 72. 99. 49.]
 [91. 87. 76. 15. 84.]]
First 3 Row: 
[[79. 87. 78.  3. 51.]
 [35. 81. 53. 97. 98.]
 [51. 34. 95. 29. 47.]]


**12.	Replace all negative numbers in an array with zero.**

In [4]:
import numpy as np
listing = [1,2,4,5,6,78,-9,-3,34]
npList = np.array(listing)
print(f"Original Array: \n{npList}")
npList[npList < 0] = 0
print(f"After Mask: \n{npList}")


Original Array: 
[ 1  2  4  5  6 78 -9 -3 34]
After Mask: 
[ 1  2  4  5  6 78  0  0 34]


**13.	Multiply two arrays element-wise.**

In [10]:
import numpy as np
listing1 = [1,2,4,45,26,78,9,34]
listing2 = [1,2,4,63,18,19,113,3]
npList1 = np.array(listing1)
npList2 = np.array(listing2)
print(f"Original List1: \n{npList1}")
print(f"Original List2: \n{npList2}")

print("x----------------------------------x")

#Approach # 01 - With * sign
multApproach1 = npList1 * npList2
#Approach # 02 - With multiply funciton
multApproach2 = np.multiply(npList1,npList2)

print(f"Approach # 01: \n{multApproach1}")
print(f"Approach # 02: \n{multApproach2}")



Original List1: 
[ 1  2  4 45 26 78  9 34]
Original List2: 
[  1   2   4  63  18  19 113   3]
x----------------------------------x
Approach # 01: 
[   1    4   16 2835  468 1482 1017  102]
Approach # 02: 
[   1    4   16 2835  468 1482 1017  102]


**14.	Find the sum, mean, and standard deviation of a 1D array.**

In [17]:
import numpy as np
oneDimArray = [1,2,3,5,6,71,123,13,13,2,3,32,21,34]
npOneDim = np.array(oneDimArray)
print(f"Original Array:\n{npOneDim}")
print(f"Sum: {np.sum(npOneDim)}")
print(f"Mean: {np.mean(npOneDim)}")
print(f"Median: {np.median(npOneDim)}")
print(f"Min: {np.min(npOneDim)}")
print(f"Max: {np.max(npOneDim)}")
print(f"Standard Deviation: {np.std(npOneDim)}")

Original Array:
[  1   2   3   5   6  71 123  13  13   2   3  32  21  34]
Sum: 329
Mean: 23.5
Median: 9.5
Min: 1
Max: 123
Standard Deviation: 33.258189109708646


**15.	Flatten a 2D array into a 1D array.**

In [24]:
import numpy as np
twoDim = [
    [1,2,4,5,67,77,1],
    [1,2,4,5,67,77,1],
]
npTwoDim = np.array(twoDim)
print(f"Original Array:\n {npTwoDim}")
print(f"Flatten Array:\n {npTwoDim.flatten()}")


Original Array:
 [[ 1  2  4  5 67 77  1]
 [ 1  2  4  5 67 77  1]]
Flatten Array:
 [ 1  2  4  5 67 77  1  1  2  4  5 67 77  1]


# **MEDIUM (16–30) – Indexing, slicing, statistics, and operations**

**16.	Create a 10×10 array and find the minimum and maximum values.**

In [29]:
import numpy as np


npArr = np.random.random((10,10))
npArrMin = npArr.min()
npArrMax = npArr.max()
print(f"Random 10x10 array: \n{npArr}")
print(f"Shape: {npArr.shape}")
print(f"Min: {npArrMin}")
print(f"Max: {npArrMax}")
print(f"Flatten: {npArr.flatten()}")
print(f"Index Of Max: {npArr.flatten().argmax()}")

Random 10x10 array: 
[[0.47474632 0.88840235 0.72961883 0.43793514 0.27843288 0.23535856
  0.11142874 0.11591238 0.21233406 0.31304746]
 [0.91040046 0.12826878 0.38236492 0.19559151 0.73143114 0.65717567
  0.61544193 0.93459098 0.38748484 0.68980883]
 [0.42353822 0.74791073 0.48946023 0.28867107 0.12849935 0.87325959
  0.7613402  0.51558476 0.20696841 0.22543464]
 [0.45749094 0.94930667 0.30780646 0.26262145 0.40373235 0.54237122
  0.33893942 0.47782441 0.24047655 0.49647516]
 [0.02309437 0.46496083 0.00315797 0.60310357 0.42703948 0.26355962
  0.53350404 0.87263927 0.96216164 0.02399904]
 [0.33607862 0.06524968 0.12444146 0.61577158 0.49684655 0.23835805
  0.16738372 0.53045679 0.41791225 0.47823439]
 [0.54734981 0.21709589 0.62054663 0.25682447 0.28792092 0.12465883
  0.94153669 0.38372682 0.2997691  0.27306619]
 [0.90908839 0.67111095 0.59162182 0.10658771 0.26456486 0.26419529
  0.95790533 0.14262247 0.34774017 0.85846892]
 [0.07883369 0.53480976 0.73840354 0.54978538 0.01642581 0.

**17.	Select all odd numbers from a 1D array of 1–20.**

In [47]:
import numpy as np
import random
num = np.random.randint(1, 20, size=20)  # 1 to 20
odd = num[num%2 !=0]
print(f"Original: {num}")
print(f"Odd: {odd}")


Original: [19  7 14 18 15 17 14  5  4  8  4 19  1  7 16 11  1  2  4 13]
Odd: [19  7 15 17  5 19  1  7 11  1 13]


**18.	Reverse a 1D array.**

In [58]:
import numpy as np
import random
oneDimNp= np.random.randint(1, 20, size=10)  # 1 to 10
print(f"Original: {oneDimNp}")
# Approach 1:
reversed = np.flip(oneDimNp)
print(f"Approach 1 - Reversed: {reversed}")
# Approach 2:
rev = oneDimNp[::-1]
print(f"Approach 2 - Reversed: {rev}")

Original: [12  7  9  6 13 15  9  5  3 10]
Approach 1 - Reversed: [10  3  5  9 15 13  6  9  7 12]
Approach 2 - Reversed: [10  3  5  9 15 13  6  9  7 12]


**19.	Extract a submatrix (2×2) from a 4×4 matrix.**

In [71]:
import numpy as np
npOriginal = np.arange(16).reshape(4,4)
print(f"Original: \n{npOriginal}")
print(f"Original Matrix Shape: {npOriginal.shape}")
subMatrix = npOriginal[0:2,0:2]
print(f"SubMatrix: \n{subMatrix}")
print(f"Sub Matrix Shape: {subMatrix.shape}")


Original: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Original Matrix Shape: (4, 4)
SubMatrix: 
[[0 1]
 [4 5]]
Sub Matrix Shape: (2, 2)


**20.	Stack two arrays vertically and horizontally.**

In [86]:
import numpy as np
numpyArr = np.arange(16).reshape(4,4)
numpyArr2 = np.arange(16,32).reshape(4,4)
print(f"Array1: \n{numpyArr}")
print(f"Array2: \n{numpyArr2}")
horizStack = np.hstack([numpyArr, numpyArr2])
print(f"Horizontal Stack: \n{horizStack}")
verStack = np.vstack([numpyArr, numpyArr2])
print(f"Vertical Stack: \n{verStack}")

Array1: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Array2: 
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
Horizontal Stack: 
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]
Vertical Stack: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
