# **NUMPY**

# **November 06, 2025 Donnerstag 00:18**

***These 50 problems cover almost every NumPy concept needed for data analytics, data science, and interviews:***

**Easy**: Basics, creation, simple operations

**Medium**: Indexing, slicing, stacking, statistics

**Hard**: Linear algebra, broadcasting, advanced operations

**Hardest**: Real-world datasets, probability, distance metrics, normalization

# **EASY (1–15) – Basics of NumPy**

***Note: I will import numpy for each task so don't think akward or something else why i am using mulitiple time***

**1.	Create a 1D array of numbers from 0 to 9.**

In [19]:
import numpy as np
npArray = np.arange(10)
print(f"Numpy Array: {npArray}")
print(f"Numpy Array Dimension: {npArray.ndim}")


Numpy Array: [0 1 2 3 4 5 6 7 8 9]
Numpy Array Dimension: 1


**2. Create a 3×3 matrix filled with zeros.**

In [13]:
import numpy as np
npZeros = np.zeros((3,3))
print(f"Numpy Zeros Array: \n {npZeros}")
print(f"Numpy Zeros Array Dimension: {npZeros.shape}")

Numpy Array: 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Numpy Array Dimension: (3, 3)


**3.	Create a 2×3 matrix filled with ones.**

In [15]:
import numpy as np
npOnes = np.ones((2,3))
print(f"Numpy Ones Array: \n {npOnes}")
print(f"Numpy Ones Array Dimension: {npOnes.shape}")

Numpy Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Numpy Ones Array Dimension: (2, 3)


**4.	Generate an array of 10 random numbers between 0 and 1.**

In [17]:
import numpy as np
rand = np.random.rand(10)
print(f"Random Between 0 to 1: \n {rand}")

Random Between 0 to 1: 
 [0.36952582 0.10828283 0.45257875 0.13176197 0.72210152 0.56146217
 0.35181388 0.92351012 0.38123495 0.13743136]


**5.	Create a 1D array of numbers from 10 to 50 with a step of 5.**

In [21]:
import numpy as np
npStepJump = np.arange(10,50,5)
print(f"Number From 10 to 50 with the Jump of 5: \n {npStepJump}")

Number From 10 to 50 with the Jump of 5: 
 [10 15 20 25 30 35 40 45]


**6.	Find the shape, size, and data type of a given array.**

In [23]:
givenArray = [1,23,12,14,15,16,16,17]
npArr = np.array(givenArray)
print(f"Shape: {npArr.shape}")
print(f"Size: {npArr.size}")
print(f"DataType: {npArr.dtype}")

Shape: (8,)
Size: 8
DataType: int64


**7.	Convert a Python list [1,2,3,4] into a NumPy array.**

In [25]:
import numpy as np
myList = [1,2,3,4,5]
npArrays = np.array(myList)
print(f"Numpy Array: \n{npArrays}")
print(f"Data Type: {type(npArrays)}")


Numpy Array: 
[1 2 3 4 5]
Data Type: <class 'numpy.ndarray'>


**8.	Reshape a 1D array of 12 elements into a 3×4 array.**

In [29]:
import numpy as np
zwölfElement = np.arange(12)
print(f"1D Array: \n{zwölfElement}")
print(f"3x4 Converted Array: \n{zwölfElement.reshape(3,4)}")

1D Array: 
[ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 Converted Array: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**9.	Create a 5×5 identity matrix.**

In [36]:
import numpy as np
identityMatrix = np.identity(5)
print(identityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


**10.	Create an array of 10 equally spaced numbers between 0 and 1.**

In [39]:
import numpy as np

equalSpace = np.linspace(0,1,10)
print(f"Eqaul Space 0 to 1: \n{equalSpace}")

Eqaul Space 0 to 1: 
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
